# Generated by Django 5.0.3 on 2024-04-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_category_name_remove_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discription',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
