# Generated by Django 5.0.3 on 2024-04-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='Item',
        ),
    ]
