# Generated by Django 5.0.3 on 2024-04-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_actor_item_writer_remove_item_actress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
