# Generated by Django 5.0.3 on 2024-04-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('MP', 'MOST-POPULAR'), ('TR', 'TOP-RATED'), ('MA', 'MOST-ANTICIPATED'), ('CS', 'COMING-SOON'), ('NA', 'NONE')], max_length=20),
        ),
    ]
