# Generated by Django 5.0.3 on 2024-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_movie_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'ACTION'), ('sci-fi', 'SCI-FI'), ('comedy', 'COMEDY'), ('thriller', 'THRILLER'), ('horror', 'HORROR'), ('drama', 'DRAMA'), ('war', 'WAR'), ('historic', 'HISTORIC'), ('documentary', 'DOCUMENTARY'), ('fantasy', 'FANTASY'), ('crime', 'CRIME'), ('sports', 'SPORTS'), ('music', 'MUSIC'), ('romance', 'ROMANCE'), ('animation', 'ANIMATION'), ('slasher', 'SLASHER'), ('adventure', 'ADVENTURE'), ('mystery', 'MYSTERY'), ('survival', 'SURVIVAL')], max_length=20),
        ),
    ]
