# Generated by Django 5.0.3 on 2024-04-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_movie_plot_alter_movie_status_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.TextField(default='Coming Soon', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(default='comming soon', null=True),
        ),
    ]
