# Generated by Django 5.0.3 on 2024-04-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_diary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('malayalam', 'MALAYALAM'), ('tamil', 'TAMIL'), ('english', 'ENGLISH'), ('telugu', 'TELUGU'), ('kannada', 'KANNADA'), ('hindi', 'HINDI'), ('korean', 'KOREAN'), ('french', 'FRENCH'), ('germen', 'GERMEN'), ('chinese', 'CHINESE'), ('japanese', 'JAPANESE')], max_length=20),
        ),
    ]
